name: valenstagram-front

services:
  front:
    image: evanhs/val-webapp:1.0
    ports:
      - "3000:3000"
    environment:
      - VITE_API_SERVER_URL='https://api.albumfamille.site/'
    networks:
      - frontend

networks:
  frontend:
    external: true
