services:
  client:
    image: evanhs/valenstagram-client:latest
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - valenstagram-network
    restart: unless-stopped

  server:
    image: evanhs/valenstagram-server:latest
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONPATH=/app
    networks:
      - valenstagram-network
    restart: unless-stopped

networks:
  valenstagram-network:
    driver: bridge

volumes:
  instance: