name: Build & push docker image

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_REPO }}

jobs:
  remote-ssh-build:
    name: Remote ssh git pull docker build commands
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands and build docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/joker/val-webapp
            git pull
            docker compose -f docker-compose.yml up -d --build
